CREATE DATABASE processEngine;
GO
ALTER DATABASE processEngine SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE processEngine SET READ_COMMITTED_SNAPSHOT ON;

EXEC sp_configure 'CONTAINED DATABASE AUTHENTICATION', 1
GO
RECONFIGURE
GO

ALTER DATABASE processEngine SET CONTAINMENT = PARTIAL;
GO

USE processEngine;
GO

CREATE USER camunda WITH PASSWORD = 'Camunda-BPM123';
GO

CREATE LOGIN camunda WITH PASSWORD = 'Camunda-BPM123';
GO